var orderHistory = [
  {
    name: 'Javascript for impatient programmers',
    orderPlaced: 'August 4, 2020',
    orderNumber: '114 - 3941689 - 8772232',
    price: 31.55,
    shipTo: 'JS Masher',
    deliveryDate: 'Aug 8, 2020',
    author: 'Rauschmayer, Dr. Axel',
    returnWindow: 'Sept 7, 2020',
    buyItAgain: 'Repurchase URL',
    viewYourItem: 'Your Items URL',
    getProductSupport: 'none',
    writeAProductReview: 'Product Review URL',
    orderDetails: 'Order Details URL',
    invoice: 'invoice URL',
    total: 34.00
  },
  {
    name: 'The Timeless Way of Building',
    orderPlaced: 'July 19, 2020',
    orderNumber: '113 - 9984268 - 1280257',
    price: 41.33,
    shipTo: 'JS Masher',
    deliveryDate: 'July 20, 2020',
    author: 'Alexander, Christopher',
    returnWindow: 'Aug 19, 2020',
    buyItAgain: 'Repurchase URL',
    viewYourItem: 'Your Items URL',
    getProductSupport: 'none',
    writeAProductReview: 'Product Review URL',
    orderDetails: 'Order Details URL',
    invoice: 'invoice URL',
    total: 44.53
  },
  {
    name: 'Gamecube Controller Adapter',
    orderPlaced: 'July 4, 2020',
    orderNumber: '114 - 2875557 - 9059409',
    price: 15.98,
    shipTo: 'JS Masher',
    deliveryDate: 'Jul 7, 2020',
    author: 'none',
    returnWindow: 'Aug 5, 2020',
    buyItAgain: 'Repurchase URL',
    viewYourItem: 'Your Items URL',
    getProductSupport: 'none',
    writeAProductReview: 'Product Review URL',
    orderDetails: 'Order Details URL',
    invoice: 'invoice URL',
    total: 17.22
  },
  {
    name: ['Gamecube Controller', 'The Art of Sql'],
    orderPlaced: 'July 3, 2020',
    orderNumber: '133 - 2883177 - 2648248',
    price: [94.95, 33.99],
    shipTo: 'JS Masher',
    deliveryDate: 'July 5, 2020',
    author: ['none', 'Faroult, Stephane'],
    returnWindow: 'Aug 4, 2020',
    buyItAgain: 'Repurchase URL',
    viewYourItem: 'Your Items URL',
    getProductSupport: 'none',
    writeAProductReview: 'Product Review URL',
    orderDetails: 'Order Details URL',
    invoice: 'invoice URL',
    total: 138.93
  }
];
